FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

WORKDIR /app-root/

RUN microdnf install --setopt=tsflags=nodocs -y python3.11 python3.11-pip which git tar xz bzip2 unzip && \
    microdnf upgrade -y && \
    microdnf clean all

RUN set -ex && if [ -e `which python3.11` ]; then ln -s `which python3.11` /usr/local/bin/python; fi

# RUN git clone -b 3.0 https://github.com/RedHatInsights/insights-core && \
#     pip3.11 install ./insights-core

RUN pip3.11 install --upgrade pip && pip3.11 install poetry
RUN poetry self add poetry-plugin-export
