# This docker compose file will stand up the minimal components necessary for
# Puptoo to work. Nothing is stood up for uploads or to consume the inventory 
# messages.
version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_SERVER_ID=1
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
  puptoo:
    image: quay.io/cloudservices/insights-puptoo:latest
    ports:
      - 8000:8000 #for prometheus endpoint
    depends_on:
      - kafka
      - minio
  minio:
      image: minio/minio
      command: ["server", "--console-address", ":9001", "/data"]
      volumes:
        - '$MINIO_DATA_DIR:/data:Z'
        - '$MINIO_CONFIG_DIR:/root/.minio:Z'
      ports:
        - 9000:9000
      environment:
        - MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
        - MINIO_SECRET_KEY=$MINIO_SECRET_KEY
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY;
      /usr/bin/mc mb myminio/insights-upload-perma;
      /usr/bin/mc mb myminio/insights-upload-rejected;
      /usr/bin/mc mb myminio/insights-upload-puptoo;
      /usr/bin/mc policy download myminio/insights-upload-perma;
      /usr/bin/mc policy download myminio/insights-upload-rejected;
      /usr/bin/mc policy download myminio/insights-upload-puptoo;
      exit 0;
      "