{
 "title": "Puptoo",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "datasource_aws", "label": "datasource_aws", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{service=\"puptoo-processor\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Successful Extractions (Advisor Service)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(puptoo_successful_extractions_total[$__range])) / sum(increase(puptoo_extractions_total[$__range]))"
    }
   ]
  },
  {
   "title": "Successful Extractions (QPC Service)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(puptoo_messages_processed_success_total{service=\"qpc\"}[$__range])) / sum(increase(puptoo_messages_processed_total{service=\"qpc\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Successful Processed Messages (All Services)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(puptoo_messages_processed_success_total[$__range])) / sum(increase(puptoo_messages_processed_total[$__range]))"
    }
   ]
  },
  {
   "title": "Total Messages Produced per Topic",
   "type": "timeseries",
   "description": "Total messages produced to each topic",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(puptoo_messages_produced_total[$__range])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Total Consumed Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(puptoo_messages_consumed_total[$__range]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Failed Extractions",
   "type": "timeseries",
   "description": "Total Uploads that failed extractions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(puptoo_failed_extractions_total[$__range]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Consumer lag",
   "type": "timeseries",
   "description": "Messages in the announce topic waiting to be picked up by Puptoo. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "aws_kafka_sum_offset_lag_sum{topic=\"platform.upload.announce\", consumer_group=\"insights-puptoo\"}",
     "legendFormat": "{{consumer_group}}"
    }
   ]
  },
  { "title": "QPC Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "QPC: Reports Downloaded",
   "type": "stat",
   "description": "Total number of QPC reports downloaded from S3",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(puptoo_qpc_archive_downloaded_success_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPC: Reports Download Failed",
   "type": "stat",
   "description": "Total number of QPC reports that failed to download",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(puptoo_qpc_archive_failed_to_download_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPC: Kafka Failures",
   "type": "stat",
   "description": "Total number of kafka failures while processing QPC messages",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(puptoo_qpc_kafka_failures_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPC: Incoming Hosts",
   "type": "stat",
   "description": "Total number of QPC hosts in report as per source",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(puptoo_qpc_incoming_hosts_counter_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPC: Report Processing Exceptions",
   "type": "stat",
   "description": "Total number of exceptions while processing QPC report",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(puptoo_qpc_report_processing_exceptions_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPC: Report Extraction Failures",
   "type": "stat",
   "description": "Total number of failures while extracting QPC report slice",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(puptoo_qpc_extract_report_slices_failures_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPC: Hosts Uploaded to HBI",
   "type": "stat",
   "description": "Total number of QPC hosts uploaded to inventory",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(puptoo_qpc_host_uploaded_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPC: Kafka Upload Failures",
   "type": "stat",
   "description": "Total number of QPC hosts that failed to upload to inventory via Kafka",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(puptoo_qpc_host_upload_failures_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPC: Hosts Missing Canonical Facts",
   "type": "stat",
   "description": "Total number of QPC hosts skipped due to missing canonical facts",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(puptoo_qpc_hosts_without_canonical_facts_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}