
name: Continuous Integration

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
    Unit-Test:
      runs-on: ubuntu-latest

      env:
        WORKSPACE: ${{ github.workspace }}
      steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Create artifacts directory
        run: mkdir -p $WORKSPACE/artifacts

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run unit tests via unit_test.sh
        run: ./unit_test.sh

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: ${{ github.workspace }}/artifacts/junit-unit_tests.xml
          retention-days: 30