
name: Continuous Integration

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
    Unit-Test:
      runs-on: ubuntu-latest

      steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run unit tests via run.sh
        run: ./run.sh
