name: renovate-config-validator
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.1.1
